### ISSUE TITLE
Cant teleport to island!

### ISSUE THREAD

**Issue by optimusprime338** [TheSolidCrafter/ASkyBlock-Nukkit#32]
### Issue Description
Write a short description about the issue
When you create new island and want to teleport island you just get stuck in spawn world and cant move etc , nothing works its just shows me directions :(.. there are not errors on console. seems like chunk generation problem but idk..

### Steps to Reproduce the Issue

1. ...
2. ...
3. ...

### OS and Versions

* ASkyBlock version:

* Nukkit Version: ?? 

* Java Version: 
```
??
```

* Host Configuration: 

* Client Configuration: 

| Item | Value |
|:----:|:-----:|
| Client Edition | ?? | 
| Client Version | ?? | 

### Crashdump, Backtrace or Other Files

```
<!--- Copy and paste your backtrace here... -->
```

**Comment by NycuRO** [comment]
@larryTheCoder I think this can fixed with one generation chunk first, and after teleport.

I think it's problem nukkit. You use player.teleport function?

**Comment by larryTheCoder** [comment]
@NycuRO yes. https://github.com/TheSolidCrafter/ASkyBlock-Nukkit/blob/master/src/main/java/com/larryTheCoder/player/TeleportLogic.java#L90
This must be Nukkit bug...

**Comment by larryTheCoder** [comment]
New update... Not tested 👎... Awaiting response from other users... Form overlay has been added and i not sure that this is a stable versions... As i said `Awaiting response`. Use `/is create` to open island overlay if bugs appears, use `/is` instead

**Comment by optimusprime338** [comment]
still same problem
