### ISSUE TITLE
Nukkit-Help Group Discord. [Helping, Performance, Informations]

### ISSUE THREAD

**Issue by NycuRO** [TheSolidCrafter/ASkyBlock-Nukkit#33]
Due to the fact that the Nukkit Team does not want to hear or is not interested in a Discourse Official Group for their Software, I decided to create a group, namely to "modify" the old one into a new one, better and especially for Nukkit.

Why do we need this group?

The group is made for all players, developers and the rest of the people interested or not by Nukkit.

I want Nukkit to be again a Good, Active and Useful Software for MCPE.

So, we're waiting for the group on the disagreement.

All developers have special grades, namely "Developers", and if they wish, they can also help the players with some information.

If you have problems or information or something else, you find me in a dispute.

Link: discord.gg/7y8WM4F

This is not an intention to promote or advertise for an action of my interest. It's just for Nukkit.

P.S. @larryTheCoder Enter here, i add and ASkyblock-Nukkit Helper Section.

**Comment by NycuRO** [comment]
Hello all. 
I decided open one Community with name "Bedrock Comunnity", replacement of Nukkit-Helping Group Discord.
This community it's created for help people with plugins, developing and others!
If you want @Members Role, you need helping with PR's on Plugins Community!
If you want @Moderators Role, you need bring players, need helping players and so so much off-topic.
Who want helping for PMMP plugins can use #support-plugins-pmmp and who want helping for NUKKIT plugins can use #support-plugins-nukkit !

Link: Group: discord.gg/7y8WM4F
Link Community: https://github.com/BedrockCommunity

Thanks for enter and good luck with servers!

**Comment by NycuRO** [comment]
@larryTheCoder Can you enter on discord, bro? 👍

**Comment by larryTheCoder** [comment]
@NycuRO I am MrPotato101#0060

**Comment by larryTheCoder** [comment]
Already did
