### ISSUE TITLE
Is create error

### ISSUE THREAD

**Issue by imjack** [TheSolidCrafter/ASkyBlock-Nukkit#34]
Hello Larry, 

If possible could you give me some method(skype/discord etc) of contact to speak to you privately I am very interested in this project.

### Issue Description
Write a short description about the issue
/is create causes some sort of gson stackoverflow 

### Steps to Reproduce the Issue

1. ... run the plugin fresh and do /is create

### OS and Versions

* ASkyBlock version: 0.3.7-BETA

* Nukkit Version:  v1.2.2 (protocol version 137)

* Java Version:  8 
* Win 10

### Crashdump, Backtrace or Other Files

```
<!--- Copy and paste your backtrace here... -->
```
https://pastebin.com/hi32npaR

**Comment by larryTheCoder** [comment]
Full stack trace please.
Discord: MrPotato101#0060

**Comment by imjack** [comment]
That is the full stack trace.

**Comment by larryTheCoder** [comment]
confirmed.

**Comment by larryTheCoder** [comment]
@imjack this problem is fixed in next commit. Because i want to test if all of it had been fixed

**Comment by imjack** [comment]
I'll have a test now, Also i can't seem to find you on discord.

**Comment by larryTheCoder** [comment]
The problem fixed in current commit.
