### ISSUE TITLE
Can't take some items from chest

### ISSUE THREAD

**Issue by PetteriM1** [TheSolidCrafter/ASkyBlock-Nukkit#37]
### Issue Description
I can't take some items from chest.

### Steps to Reproduce the Issue
1. Create new island.
2. Try to take all items from chest.

### OS and Versions

* ASkyBlock version: last

* Nukkit Version: 1.2.x 

* Java Version: idk

* Host Configuration: 

* Client Configuration: 

| Item | Value |
|:----:|:-----:|
| Client Edition |Windows 10 | 
| Client Version | 1.2.8 | 

### Crashdump, Backtrace or Other Files
no

**Comment by PetteriM1** [comment]
Even when using PE schematic it don't work. If I try to use chest items in config it work but you can get only one item per type and you can't use most items to anything because there is bug with item metadata.

My solution: I created my own version of this plugin for my server and fixed these bugs.

PS. If you need fixed schematics example that two island schematic look from fork in Nukkit Coders Github page.

**Comment by NycuRO** [comment]
@larryTheCoder I know one.

When paste a schematic, remove all items from chest and put what you want 👍 
But be sure chunks is loaded, if you want to work <3

**Comment by NycuRO** [comment]
Or:

Remove chests from schematics and add them yourself when chunks are loaded. (with code)
I suggest you use player spawned position on schematic for find where yo place chest :>
