### ISSUE TITLE
ASkyBlock - 1.2.10

### ISSUE THREAD

**Issue by UnexMC** [TheSolidCrafter/ASkyBlock-Nukkit#38]
Do you have a Nukkit Version where ASkyblock work with?

**Comment by larryTheCoder** [comment]
Try this one https://github.com/NukkitX/Nukkit

**Comment by PetteriM1** [comment]
@larryTheCoder This plugin don't work with NukkitX

**Comment by larryTheCoder** [comment]
Hmm its seems like this plugin too old... And there is some fix for it that i working on it. Oh this project still **continued**

**Comment by larryTheCoder** [comment]
The bug had been fixed
