### ISSUE TITLE
Teleport to other Island

### ISSUE THREAD

**Issue by UnexMC** [TheSolidCrafter/ASkyBlock-Nukkit#45]
15:59:22 [CRITICAL] Unhandled exception executing command 'is teleport HappyLea13' in is: java.lang.NullPointerException        at com.larryTheCoder.island.IslandManager.teleportPlayer(IslandManager.java:334)         at com.larryTheCoder.command.island.TeleportSubCommand.execute(TeleportSubCommand.java:65)         at com.larryTheCoder.Commands.execute(Commands.java:105)         at cn.nukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:261)         at cn.nukkit.Server.dispatchCommand(Server.java:690)         at cn.nukkit.Player.handleDataPacket(Player.java:2632)         at java.util.ArrayList.forEach(ArrayList.java:1257)         at cn.nukkit.network.Network.processPackets(Network.java:178)         at cn.nukkit.network.Network.processBatch(Network.java:160)         at cn.nukkit.Player.handleDataPacket(Player.java:2025)         at cn.nukkit.network.RakNetInterface.handleEncapsulated(RakNetInterface.java:157)         at cn.nukkit.raknet.server.ServerHandler.handlePacket(ServerHandler.java:132)         at cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:66)         at cn.nukkit.network.Network.processInterfaces(Network.java:76)         at cn.nukkit.Server.tick(Server.java:1076)         at cn.nukkit.Server.tickProcessor(Server.java:850)         at cn.nukkit.Server.start(Server.java:827)         at cn.nukkit.Server.<init>(Server.java:510)         at cn.nukkit.Nukkit.main(Nukkit.java:99)  15:59:22 [ALERT] java.lang.NullPointerException         at com.larryTheCoder.island.IslandManager.teleportPlayer(IslandManager.java:334)         at com.larryTheCoder.command.island.TeleportSubCommand.execute(TeleportSubCommand.java:65)         at com.larryTheCoder.Commands.execute(Commands.java:105)         at cn.nukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:261)         at cn.nukkit.Server.dispatchCommand(Server.java:690)         at cn.nukkit.Player.handleDataPacket(Player.java:2632)         at java.util.ArrayList.forEach(ArrayList.java:1257)         at cn.nukkit.network.Network.processPackets(Network.java:178)         at cn.nukkit.network.Network.processBatch(Network.java:160)         at cn.nukkit.Player.handleDataPacket(Player.java:2025)         at cn.nukkit.network.RakNetInterface.handleEncapsulated(RakNetInterface.java:157)         at cn.nukkit.raknet.server.ServerHandler.handlePacket(ServerHandler.java:132)         at cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:66)         at cn.nukkit.network.Network.processInterfaces(Network.java:76)         at cn.nukkit.Server.tick(Server.java:1076)         at cn.nukkit.Server.tickProcessor(Server.java:850)         at cn.nukkit.Server.start(Server.java:827)         at cn.nukkit.Server.<init>(Server.java:510)         at cn.nukkit.Nukkit.main(Nukkit.java:99)

**Comment by larryTheCoder** [comment]
I really need to fix the reporting issue formatting, and yes it not working yet. Check back the repo later, maybe I will include a fix for that
