### ISSUE TITLE
Latest update breaks IS Claiming

### ISSUE THREAD

**Issue by Cobwebster** [TheSolidCrafter/ASkyBlock-Nukkit#49]
https://pastebin.com/xdiApbR3

this is a follow up of this issue, https://github.com/TheSolidCrafter/ASkyBlock-Nukkit/issues/44

looks like the attempt for fix that broke IS claiming and didn't actually fix protection.

**Comment by PetteriM1** [comment]
This is because no all things are updated to work with NukkitX correctly

**Comment by Cobwebster** [comment]
Sorry, so basically when using the /is command to make a new IS on a fresh setup it denies it and throws that error, by IS claiming I meant using /is to grab yourself a IS.

**Comment by larryTheCoder** [comment]
Are you using other world instead of SkyBlock world? Because I found some leak on /is gen

**Comment by larryTheCoder** [comment]
What seems like... You are using the old builds. Uh huh. Now I getting clear. Try to use new one. See the diffrent

**Comment by Cobwebster** [comment]
I got linked the latest version in the discord, is creation works but the protection issue is still around with the same error, it seems the plugin just doesn't work with nukkit. i'm being told to use different versions of nukkit to support skyblock, i talked in the nukkit chat and they say that askyblock is at fault for the errors since i suggested nukkit chunking loading might have a factor.
