### ISSUE TITLE
Bug file.schematic

### ISSUE THREAD

**Issue by vuahackervn** [TheSolidCrafter/ASkyBlock-Nukkit#53]
Error file.schematic on 0.4.8 and no error 0.4.7 plsss fix new 0.4.9
Im From Vietnamese and friend of adam1609
We support you

**Comment by larryTheCoder** [comment]
file.schematic is error? What are you trying to do?

**Comment by vuahackervn** [comment]
im download file skyblock.schematic on pc run on 0.4.7 no bugs, but 0.4.8 run skyblock.schematic bugs error and im tp world SkyBlock it was created ?.?? I need the reason

**Comment by larryTheCoder** [comment]
bugs occurs** can you PLEASE reproduce what happens? WHAT error? At least just post something that I could explain what is your issue

**Comment by vuahackervn** [comment]
For example, I downloaded a pc's .schematic file for ASkyblock. I ran it with version 0.4.7 successfully. But, to version 0.4.8 it does not work. Some of the errors that I found out again / isa setspawn it does not work every version. And last year I thought the error was because you added something new in version 0.4.8. If it is fixed, then I sincerely thank you very much. If you can not fix it, it's okay. Thank you

**Comment by larryTheCoder** [comment]
Ah, so is there a message saying 'Cannot attempt to generate level. PC Type of schematic'?

**Comment by vuahackervn** [comment]
Yes, you can fix it. Besides that I do not ask for anything more, and as MCPE you should give something down. Because of MCPE it has limits. What you need to put in, you do not need to delete. thank you

**Comment by larryTheCoder** [comment]
Its should be fixed in the latest build now
