### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by BeanGTA** [TheSolidCrafter/ASkyBlock-Nukkit#54]
Water and lava error

**Comment by BeanGTA** [comment]
Water takes lava

**Comment by BeanGTA** [comment]
Ok wait for me

**Comment by BeanGTA** [comment]
https://youtu.be/gfVsGT23__w

**Comment by PetteriM1** [comment]
1. This is not skyblock plugin's bug
2. You made the cobble generator wrong (there is no hole where the water goes)

**Comment by BeanGTA** [comment]
Im run 0.4.8 no bug block

**Comment by larryTheCoder** [comment]
The way how generator work is not the same with the original skyblock plugin. You need to have some space to make it work. The generator still under development and will be improved by time.

**Comment by BeanGTA** [comment]
Ok.

**Comment by larryTheCoder** [comment]
How about now? You got the problem fixed?

**Comment by BeanGTA** [comment]
Fixed by the mutilworld plugins, but added more errors

Vào 15:48, Th 4, 10 thg 10, 2018 Adam Matthew <notifications@github.com> đã
viết:

**Comment by BeanGTA** [comment]
In ASkyBlock it is not compatible with mutilworld

Vào 15:52, Th 4, 10 thg 10, 2018 Tiến Bean <beanvietnammcpe@gmail.com> đã
viết:

**Comment by larryTheCoder** [comment]
ASkyBlock is not currently compatible with any plugins at this moment. I am sure that the plugin issue and not mine

**Comment by larryTheCoder** [comment]
And if you could, could you give me trace log of the issue, It could help

**Comment by BeanGTA** [comment]
I deleted the world named SkyBlock, deleted all Askyblock in the plugins
directory, and I ran it ended up not moving to the SkyBlock world. I think
it is faulty in the Players Directory

Vào 15:55, Th 4, 10 thg 10, 2018 Adam Matthew <notifications@github.com> đã
viết:

**Comment by BeanGTA** [comment]
I tried version 0.4.8 it was not faulty, it just crashed in schematics, can
not run the PC's file.schematic

Vào 15:57, Th 4, 10 thg 10, 2018 Tiến Bean <beanvietnammcpe@gmail.com> đã
viết:

**Comment by larryTheCoder** [comment]
I mean the development build. You can download the jar from my CircleCI

**Comment by BeanGTA** [comment]
Version 0.4.9, it failed, the whole set

Vào 16:02, Th 4, 10 thg 10, 2018 Adam Matthew <notifications@github.com> đã
viết:

**Comment by BeanGTA** [comment]
.jar good but 0.4.8 error load file.schematic on pc

Vào 16:03, Th 4, 10 thg 10, 2018 Tiến Bean <beanvietnammcpe@gmail.com> đã
viết:

**Comment by BeanGTA** [comment]
You go server my test plugins ASkyBlock by you
IP: play.mrface.com
Port: 19132

Vào 16:04, Th 4, 10 thg 10, 2018 Tiến Bean <beanvietnammcpe@gmail.com> đã
viết:

**Comment by BeanGTA** [comment]
https://i.loli.net/2018/10/11/5bbe2b49b760e.png
https://i.loli.net/2018/10/11/5bbe2b49de045.png

To the other people to fault

Now I discovered a lot of bugs all plugins, if I make holes support server nukkit
As I can get all the Server information

**Comment by larryTheCoder** [comment]
Hmm, I suggest to use the latest development build for this, the code is
unstable... Sometimes its work and sometimes its don't
